all:
  vars:
    ansible_user: admin
    ansible_password: NokiaSrl1!

  children:
    nokia_srl_jsonrpc:
      vars:
        ansible_connection: ansible.netcommon.httpapi
        ansible_network_os: nokia.srlinux.srlinux

      hosts:

        clab-auto_lab_02_bis-r1:
          interface:
            ethernet-1/1:
              description: TO_PC1
              admin_state: enable
              subinterface:
                "0":
                  admin_state: enable
                  ipv4:
                    admin_state: enable
                    address: 192.168.1.1/24
            ethernet-1/55:
              description: TO_R2
              admin_state: enable
              subinterface:
                "0":
                  admin_state: enable
                  ipv4:
                    admin_state: enable
                    address: 99.1.2.1/30
            ethernet-1/56:
              description: TO_R3
              admin_state: enable
              subinterface:
                "0":
                  admin_state: enable
                  ipv4:
                    admin_state: enable
                    address: 99.1.3.1/30
            
          network_instance:
            default:
              interface:
                - ethernet-1/1.0
                - ethernet-1/55.0
                - ethernet-1/56.0
              protocols:
                ospf:
                  default: # Instance name
                    admin_state: enable
                    version: ospf-v2
                    router_id: 99.0.0.1
                    area:
                      0.0.0.0:
                        interface:
                          ethernet-1/1.0:
                            interface_type: point-to-point
                            passive: "true"
                          ethernet-1/55.0:
                            interface_type: point-to-point
                          ethernet-1/56.0:
                            interface_type: point-to-point

    nokia_srl_netconf:
      vars:
        ansible_connection: ansible.netcommon.netconf
        ansible_network_os: nokia.srlinux.srlinux

      hosts:

        clab-auto_lab_02_bis-r2:
          interface:
            ethernet-1/1:
              description: TO_PC1
              admin_state: enable
              subinterface:
                "0":
                  admin_state: enable
                  ipv4:
                    admin_state: enable
                    address: 192.168.2.1/24
            ethernet-1/55:
              description: TO_R1
              admin_state: enable
              subinterface:
                "0":
                  admin_state: enable
                  ipv4:
                    admin_state: enable
                    address: 99.1.2.2/30
            ethernet-1/56:
              description: TO_R3
              admin_state: enable
              subinterface:
                "0":
                  admin_state: enable
                  ipv4:
                    admin_state: enable
                    address: 99.2.3.1/30
            
          network_instance:
            default:
              interface:
                - ethernet-1/1.0
                - ethernet-1/55.0
                - ethernet-1/56.0
              protocols:
                ospf:
                  default: # Instance name
                    admin_state: enable
                    version: ospf-v2
                    router_id: 99.0.0.2
                    area:
                      0.0.0.0:
                        interface:
                          ethernet-1/1.0:
                            interface_type: point-to-point
                            passive: "true"
                          ethernet-1/55.0:
                            interface_type: point-to-point
                          ethernet-1/56.0:
                            interface_type: point-to-point

        clab-auto_lab_02_bis-r3:
          interface:
            ethernet-1/1:
              description: TO_PC1
              admin_state: enable
              subinterface:
                "0":
                  admin_state: enable
                  ipv4:
                    admin_state: enable
                    address: 192.168.3.1/24
            ethernet-1/55:
              description: TO_R1
              admin_state: enable
              subinterface:
                "0":
                  admin_state: enable
                  ipv4:
                    admin_state: enable
                    address: 99.1.3.2/30
            ethernet-1/56:
              description: TO_R2
              admin_state: enable
              subinterface:
                "0":
                  admin_state: enable
                  ipv4:
                    admin_state: enable
                    address: 99.2.3.2/30
            
          network_instance:
            default:
              interface:
                - ethernet-1/1.0
                - ethernet-1/55.0
                - ethernet-1/56.0
              protocols:
                ospf:
                  default: # Instance name
                    admin_state: enable
                    version: ospf-v2
                    router_id: 99.0.0.3
                    area:
                      0.0.0.0:
                        interface:
                          ethernet-1/1.0:
                            interface_type: point-to-point
                            passive: "true"
                          ethernet-1/55.0:
                            interface_type: point-to-point
                          ethernet-1/56.0:
                            interface_type: point-to-point

                            