all:
  children:
    vyos:
      vars:
        # The following values are needed only for CLI deployment
        ansible_network_os: vyos
        ansible_connection: network_cli
        ansible_user: admin
        ansible_ssh_pass: admin

        global_config:
          interfaces:
            ethernet:
              eth1:
               description: "Backbone Interface"
              eth2:
               description: "Backbone Interface"
              eth3:
                description: "Backbone Interface"

          protocols:
            isis:
              level: level-2
              log-adjacency-changes:
              metric-style: wide
              interface:
                eth1:
                  network: point-to-point
                eth2:
                  network: point-to-point
                eth3:
                  network: point-to-point
                dum0:
                  passive:

              segment-routing:
                srv6:
                  locator:
                    L3VPN:

            segment-routing:
              interface:
                eth1:
                  srv6:
                eth2:
                  srv6:
                eth3:
                  srv6:
              srv6:
                locator:
                  L3VPN:
                    behavior-usid:


      hosts:
        clab-internet_02-PE1:
          specific_config:
            interfaces:
              dummy:
                dum0:
                  address: '2001:db8::1/128'

            protocols:
              isis:
                net: '49.0000.0000.0000.0001.00'
                  
              segment-routing:
                srv6:
                  locator:
                    L3VPN:
                      prefix: '2001:db8:100:1::/64'

        clab-internet_02-PE2:
          specific_config:
            interfaces:
              dummy:
                dum0:
                  address: '2001:db8::2/128'

            protocols:
              isis:
                net: '49.0000.0000.0000.0002.00'

              segment-routing:
                srv6:
                  locator:
                    L3VPN:
                      prefix: '2001:db8:100:2::/64'

        clab-internet_02-PE3:
          specific_config:
            interfaces:
              dummy:
                dum0:
                  address: '2001:db8::3/128'

            protocols:
              isis:
                net: '49.0000.0000.0000.0003.00'

              segment-routing:
                srv6:
                  locator:
                    L3VPN:
                      prefix: '2001:db8:100:3::/64'

        clab-internet_02-PE4:
          specific_config:
            interfaces:
              dummy:
                dum0:
                  address: '2001:db8::4/128'

            protocols:
              isis:
                net: '49.0000.0000.0000.0004.00'

              segment-routing:
                srv6:
                  locator:
                    L3VPN:
                      prefix: '2001:db8:100:4::/64'