all:
  children:
    nokia_srl:
      vars:
        ansible_user: admin
        ansible_password: NokiaSrl1!
        ansible_connection: ansible.netcommon.httpapi
        ansible_network_os: nokia.srlinux.srlinux

      hosts:
        clab-auto_lab_02-r1:
          interfaces:
            - interface_name: ethernet-1/1
              description: TO_PC1
              admin_state: enable
            - interface_name: "ethernet-1/55"
              description: TO_R2
              admin_state: enable
            - interface_name: "ethernet-1/56"
              description: TO_R3
              admin_state: enable

          ipv4_subinterfaces:
            - interface_name: ethernet-1/1
              subinterface_index: 0
              admin_state: enable
              ipv4:
                admin_state: enable
                address: 192.168.1.1/24
            - interface_name: "ethernet-1/55"
              subinterface_index: 0
              admin_state: enable
              ipv4:
                admin_state: enable
                address: 99.1.2.1/30
            - interface_name: "ethernet-1/56"
              subinterface_index: 0
              admin_state: enable
              ipv4:
                admin_state: enable
                address: 99.1.3.1/30

          interface_bindings:
            - network_instance: "default"
              interface_name: "ethernet-1/1.0" 
            - network_instance: "default"
              interface_name: "ethernet-1/55.0"
            - network_instance: "default"
              interface_name: "ethernet-1/56.0"

          ospf_instances:
            - network_instance: "default"
              ospf_instance: "default"
              admin_state: enable
              version: "ospf-v2"
              router_id: "99.0.0.1"

          ospf_area_interfaces:
            - network_instance: "default"
              ospf_instance: "default"
              area_id: "0.0.0.0"
              interface_name: "ethernet-1/1.0"
              interface_type: "point-to-point"
              passive: true
            - network_instance: "default"
              ospf_instance: "default"
              area_id: "0.0.0.0"
              interface_name: "ethernet-1/55.0"
              interface_type: "point-to-point"
            - network_instance: "default"
              ospf_instance: "default"
              area_id: "0.0.0.0"
              interface_name: "ethernet-1/56.0"
              interface_type: "point-to-point"
            

        clab-auto_lab_02-r2:
          interfaces:
            - interface_name: ethernet-1/1
              description: TO_PC2
              admin_state: enable
            - interface_name: "ethernet-1/55"
              description: TO_R1
              admin_state: enable
            - interface_name: "ethernet-1/56"
              description: TO_R3
              admin_state: enable

          ipv4_subinterfaces:
            - interface_name: ethernet-1/1
              subinterface_index: 0
              admin_state: enable
              ipv4:
                admin_state: enable
                address: 192.168.2.1/24
            - interface_name: "ethernet-1/55"
              subinterface_index: 0
              admin_state: enable
              ipv4:
                admin_state: enable
                address: 99.1.2.2/30
            - interface_name: "ethernet-1/56"
              subinterface_index: 0
              admin_state: enable
              ipv4:
                admin_state: enable
                address: 99.2.3.1/30

          interface_bindings:
            - network_instance: "default"
              interface_name: "ethernet-1/1.0" 
            - network_instance: "default"
              interface_name: "ethernet-1/55.0"
            - network_instance: "default"
              interface_name: "ethernet-1/56.0"

          ospf_instances:
            - network_instance: "default"
              ospf_instance: "default"
              admin_state: enable
              version: "ospf-v2"
              router_id: "99.0.0.2"

          ospf_area_interfaces:
            - network_instance: "default"
              ospf_instance: "default"
              area_id: "0.0.0.0"
              interface_name: "ethernet-1/1.0"
              interface_type: "point-to-point"
              passive: true
            - network_instance: "default"
              ospf_instance: "default"
              area_id: "0.0.0.0"
              interface_name: "ethernet-1/55.0"
              interface_type: "point-to-point"
            - network_instance: "default"
              ospf_instance: "default"
              area_id: "0.0.0.0"
              interface_name: "ethernet-1/56.0"
              interface_type: "point-to-point"


        clab-auto_lab_02-r3:
          interfaces:
            - interface_name: ethernet-1/1
              description: TO_PC3
              admin_state: enable
            - interface_name: "ethernet-1/55"
              description: TO_R1
              admin_state: enable
            - interface_name: "ethernet-1/56"
              description: TO_R2
              admin_state: enable

          ipv4_subinterfaces:
            - interface_name: ethernet-1/1
              subinterface_index: 0
              admin_state: enable
              ipv4:
                admin_state: enable
                address: 192.168.3.1/24
            - interface_name: "ethernet-1/55"
              subinterface_index: 0
              admin_state: enable
              ipv4:
                admin_state: enable
                address: 99.1.3.2/30
            - interface_name: "ethernet-1/56"
              subinterface_index: 0
              admin_state: enable
              ipv4:
                admin_state: enable
                address: 99.2.3.2/30

          interface_bindings:
            - network_instance: "default"
              interface_name: "ethernet-1/1.0" 
            - network_instance: "default"
              interface_name: "ethernet-1/55.0"
            - network_instance: "default"
              interface_name: "ethernet-1/56.0"

          ospf_instances:
            - network_instance: "default"
              ospf_instance: "default"
              admin_state: enable
              version: "ospf-v2"
              router_id: "99.0.0.3"

          ospf_area_interfaces:
            - network_instance: "default"
              ospf_instance: "default"
              area_id: "0.0.0.0"
              interface_name: "ethernet-1/1.0"
              interface_type: "point-to-point"
              passive: true
            - network_instance: "default"
              ospf_instance: "default"
              area_id: "0.0.0.0"
              interface_name: "ethernet-1/55.0"
              interface_type: "point-to-point"
            - network_instance: "default"
              ospf_instance: "default"
              area_id: "0.0.0.0"
              interface_name: "ethernet-1/56.0"
              interface_type: "point-to-point"


