---
- name: Deploy VyOS config from inventory
  hosts: vyos
  gather_facts: false

  tasks:

  - name: Merge global and specific configurations
    set_fact:
      merged_config: "{{ global_config | deepmerge(specific_config) }}"

  - name: Parse global config using vyos_parser filter
    set_fact:
      vyos_config: "{{ merged_config | vyos_parser }}"

  - name: Debug parsed configuration
    debug:
      var: vyos_config

  - name: Build operations payload in VyOS API format
    set_fact:
      vyos_ops: |
        {% set out = [] %}
        {% for p in vyos_config %}
        {% set _ = out.append( { 'op': 'set', 'path': p }) %}
        {% endfor %}
        {{ out }}

  - name: Debug payload
    debug:
      var: vyos_ops

  - name: Send configuration to VyOS API
    uri:
      url: "https://{{ inventory_hostname }}/configure"
      method: POST
      body_format: form-multipart
      body:
        data: "{{ vyos_ops | to_json }}"
        key: "admin"
      validate_certs: no
    register: result

  - name: Debug API response
    debug:
      var: result.status

